# Generated by Django 5.2.8 on 2025-11-23 21:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=13, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_churches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Church',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLERGY', 'Clergy'), ('TREASURER', 'Treasurer'), ('VOLUNTEER', 'Volunteer'), ('INTERN', 'Intern')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['church', 'role'], name='core_church_church__d0f1ff_idx'), models.Index(fields=['user', 'role'], name='core_church_user_id_cb6d4a_idx')],
                'unique_together': {('user', 'church', 'role')},
            },
        ),
    ]
